spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authguard
    username: postgres
    password: your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false # development only
  main:
    banner-mode: "off"

auth:
  jwt:
    secret: your_secret
    expiration: 86400000 # 1 day (24 * 60 * 60 * 1000)

server:
  port: 8080